---
title: "Introduction to ppendemic"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = FALSE,
  out.width = "100%"
)
```


```{r setup, include=FALSE}
library(tidyverse)
library(ppendemic)
theme_set(theme_minimal())
```




## Examples:

`pep_check`, the basic function of `ppendemic`:

```{r example, eval=FALSE}
library(tidyverse)
library(ppendemic)
```

The function can be executed on a `vector` with the names of the species to be verified.

```{r spp-vector}
spp <-  c("Clethra cuneata", "Miconia setulosa", "Weinmannia fagaroides", "Symplocos quitensis", "Miconia alpina", "Persea ruizii", "Myrsine andina", "Symplocos baehnii", "Polylepis pauta")

pep_check(spp)

```

Or in a tibble variable:

```{r spp-tibble}
df <- tibble::tibble(sppe = c("Clethra cuneata", "Miconia setulosa",
                          "Weinmannia fagaroides", "Symplocos quitensis",
                          "Miconia alpina", "Persea ruizii",
                          "Myrsine andina", "Symplocos baehnii",
                          "Polylepis pauta"))

df

df %>% 
  mutate(endemic = pep_check(sppe))
```

You can check the region where the endemic species are registered with `pep_regdep` function:

```{r regdep}
pep_regdep("Miconia alpina")

```


and build a map with `pep_regdep_map()`:

```{r map}
pep_regdep_map("Miconia alpina")

```

`pep_by_reg()` give access a list of species by region or regions 

```{r pep_by}
pep_by_reg("Cusco")

# or

pep_by_reg(c("Cusco", "Madre de Dios"))
```
